// Date: 18.06.2018 16:23:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelDwarfsHelmet extends ModelBase
{
  //fields
    ModelRenderer Shtuka_speredi;
    ModelRenderer Shtuka_szadi;
    ModelRenderer Shtuka_sverhu1;
    ModelRenderer Shtuka_svehu2;
    ModelRenderer Brov-R;
    ModelRenderer Brov-L;
    ModelRenderer Rpg-R0;
    ModelRenderer Rog-R1;
    ModelRenderer Rog-R1-2;
    ModelRenderer Rog-R2;
    ModelRenderer Rog-R2-3;
    ModelRenderer Rog-R3;
    ModelRenderer Rog-R4;
    ModelRenderer Rog-R5;
    ModelRenderer Rog-L0;
    ModelRenderer Rog-L1;
    ModelRenderer Rog-L1-2;
    ModelRenderer Rog-L2;
    ModelRenderer Rog-L2-3;
    ModelRenderer Rog-L3;
    ModelRenderer Rog-L4;
    ModelRenderer Rog-L5;
    ModelRenderer head;
  
  public ModelDwarfsHelmet()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shtuka_speredi = new ModelRenderer(this, 24, 1);
      Shtuka_speredi.addBox(0F, 0F, 0F, 2, 6, 1);
      Shtuka_speredi.setRotationPoint(-1F, -10F, -5F);
      Shtuka_speredi.setTextureSize(64, 32);
      Shtuka_speredi.mirror = true;
      setRotation(Shtuka_speredi, 0F, 0F, 0F);
      Shtuka_szadi = new ModelRenderer(this, 30, 3);
      Shtuka_szadi.addBox(0F, 0F, 0F, 2, 4, 1);
      Shtuka_szadi.setRotationPoint(-1F, -10F, 4F);
      Shtuka_szadi.setTextureSize(64, 32);
      Shtuka_szadi.mirror = true;
      setRotation(Shtuka_szadi, 0F, 0F, 0F);
      Shtuka_sverhu1 = new ModelRenderer(this, 32, 0);
      Shtuka_sverhu1.addBox(0F, 0F, 0F, 2, 2, 8);
      Shtuka_sverhu1.setRotationPoint(-1F, -10F, -4F);
      Shtuka_sverhu1.setTextureSize(64, 32);
      Shtuka_sverhu1.mirror = true;
      setRotation(Shtuka_sverhu1, 0F, 0F, 0F);
      Shtuka_svehu2 = new ModelRenderer(this, 44, 2);
      Shtuka_svehu2.addBox(0F, 0F, 0F, 1, 1, 8);
      Shtuka_svehu2.setRotationPoint(-0.5F, -10.5F, -4F);
      Shtuka_svehu2.setTextureSize(64, 32);
      Shtuka_svehu2.mirror = true;
      setRotation(Shtuka_svehu2, 0F, 0F, 0F);
      Brov-R = new ModelRenderer(this, 30, 1);
      Brov-R.addBox(0F, 0F, 0F, 2, 1, 1);
      Brov-R.setRotationPoint(-3F, -6F, -5F);
      Brov-R.setTextureSize(64, 32);
      Brov-R.mirror = true;
      setRotation(Brov-R, 0F, 0F, 0F);
      Brov-L.mirror = true;
      Brov-L = new ModelRenderer(this, 30, 1);
      Brov-L.addBox(0F, 0F, 0F, 2, 1, 1);
      Brov-L.setRotationPoint(1F, -6F, -5F);
      Brov-L.setTextureSize(64, 32);
      Brov-L.mirror = true;
      setRotation(Brov-L, 0F, 0F, 0F);
      Brov-L.mirror = false;
      Rpg-R0 = new ModelRenderer(this, 32, 10);
      Rpg-R0.addBox(0F, 0F, 0F, 1, 3, 3);
      Rpg-R0.setRotationPoint(-5F, -5.5F, -1.5F);
      Rpg-R0.setTextureSize(64, 32);
      Rpg-R0.mirror = true;
      setRotation(Rpg-R0, 0F, 0F, 0F);
      Rog-R1 = new ModelRenderer(this, 0, 28);
      Rog-R1.addBox(0F, 0F, 0F, 4, 2, 2);
      Rog-R1.setRotationPoint(-8F, -5F, -1F);
      Rog-R1.setTextureSize(64, 32);
      Rog-R1.mirror = true;
      setRotation(Rog-R1, 0F, 0F, 0F);
      Rog-R1-2 = new ModelRenderer(this, 0, 25);
      Rog-R1-2.addBox(0F, 0F, 0F, 1, 1, 2);
      Rog-R1-2.setRotationPoint(-8F, -6F, -1F);
      Rog-R1-2.setTextureSize(64, 32);
      Rog-R1-2.mirror = true;
      setRotation(Rog-R1-2, 0F, 0F, 0F);
      Rog-R2 = new ModelRenderer(this, 0, 21);
      Rog-R2.addBox(0F, 0F, 0F, 2, 2, 2);
      Rog-R2.setRotationPoint(-10F, -6F, -1F);
      Rog-R2.setTextureSize(64, 32);
      Rog-R2.mirror = true;
      setRotation(Rog-R2, 0F, 0F, 0F);
      Rog-R2-3 = new ModelRenderer(this, 12, 24);
      Rog-R2-3.addBox(0F, 0F, 0F, 1, 6, 2);
      Rog-R2-3.setRotationPoint(-11F, -11F, -1F);
      Rog-R2-3.setTextureSize(64, 32);
      Rog-R2-3.mirror = true;
      setRotation(Rog-R2-3, 0F, 0F, 0F);
      Rog-R3 = new ModelRenderer(this, 12, 16);
      Rog-R3.addBox(0F, 0F, 0F, 1, 6, 2);
      Rog-R3.setRotationPoint(-10F, -12F, -1F);
      Rog-R3.setTextureSize(64, 32);
      Rog-R3.mirror = true;
      setRotation(Rog-R3, 0F, 0F, 0F);
      Rog-R4 = new ModelRenderer(this, 18, 28);
      Rog-R4.addBox(0F, 0F, 0F, 1, 2, 2);
      Rog-R4.setRotationPoint(-9F, -12F, -1F);
      Rog-R4.setTextureSize(64, 32);
      Rog-R4.mirror = true;
      setRotation(Rog-R4, 0F, 0F, 0F);
      Rog-R5 = new ModelRenderer(this, 18, 26);
      Rog-R5.addBox(0F, 0F, 0F, 1, 1, 1);
      Rog-R5.setRotationPoint(-8F, -11.5F, -0.5F);
      Rog-R5.setTextureSize(64, 32);
      Rog-R5.mirror = true;
      setRotation(Rog-R5, 0F, 0F, 0F);
      Rog-L0 = new ModelRenderer(this, 32, 10);
      Rog-L0.addBox(0F, 0F, 0F, 1, 3, 3);
      Rog-L0.setRotationPoint(4F, -5.5F, -1.5F);
      Rog-L0.setTextureSize(64, 32);
      Rog-L0.mirror = true;
      setRotation(Rog-L0, 0F, 0F, 0F);
      Rog-L1.mirror = true;
      Rog-L1 = new ModelRenderer(this, 0, 28);
      Rog-L1.addBox(0F, 0F, 0F, 4, 2, 2);
      Rog-L1.setRotationPoint(4F, -5F, -1F);
      Rog-L1.setTextureSize(64, 32);
      Rog-L1.mirror = true;
      setRotation(Rog-L1, 0F, 0F, 0F);
      Rog-L1.mirror = false;
      Rog-L1-2.mirror = true;
      Rog-L1-2 = new ModelRenderer(this, 0, 25);
      Rog-L1-2.addBox(0F, 0F, 0F, 1, 1, 2);
      Rog-L1-2.setRotationPoint(7F, -6F, -1F);
      Rog-L1-2.setTextureSize(64, 32);
      Rog-L1-2.mirror = true;
      setRotation(Rog-L1-2, 0F, 0F, 0F);
      Rog-L1-2.mirror = false;
      Rog-L2.mirror = true;
      Rog-L2 = new ModelRenderer(this, 0, 21);
      Rog-L2.addBox(0F, 0F, 0F, 2, 2, 2);
      Rog-L2.setRotationPoint(8F, -6F, -1F);
      Rog-L2.setTextureSize(64, 32);
      Rog-L2.mirror = true;
      setRotation(Rog-L2, 0F, 0F, 0F);
      Rog-L2.mirror = false;
      Rog-L2-3.mirror = true;
      Rog-L2-3 = new ModelRenderer(this, 12, 24);
      Rog-L2-3.addBox(0F, 0F, 0F, 1, 6, 2);
      Rog-L2-3.setRotationPoint(10F, -11F, -1F);
      Rog-L2-3.setTextureSize(64, 32);
      Rog-L2-3.mirror = true;
      setRotation(Rog-L2-3, 0F, 0F, 0F);
      Rog-L2-3.mirror = false;
      Rog-L3 = new ModelRenderer(this, 12, 16);
      Rog-L3.addBox(0F, 0F, 0F, 1, 6, 2);
      Rog-L3.setRotationPoint(9F, -12F, -1F);
      Rog-L3.setTextureSize(64, 32);
      Rog-L3.mirror = true;
      setRotation(Rog-L3, 0F, 0F, 0F);
      Rog-L4.mirror = true;
      Rog-L4 = new ModelRenderer(this, 18, 28);
      Rog-L4.addBox(0F, 0F, 0F, 1, 2, 2);
      Rog-L4.setRotationPoint(8F, -12F, -1F);
      Rog-L4.setTextureSize(64, 32);
      Rog-L4.mirror = true;
      setRotation(Rog-L4, 0F, 0F, 0F);
      Rog-L4.mirror = false;
      Rog-L5.mirror = true;
      Rog-L5 = new ModelRenderer(this, 18, 26);
      Rog-L5.addBox(0F, 0F, 0F, 1, 1, 1);
      Rog-L5.setRotationPoint(7F, -11.5F, -0.5F);
      Rog-L5.setTextureSize(64, 32);
      Rog-L5.mirror = true;
      setRotation(Rog-L5, 0F, 0F, 0F);
      Rog-L5.mirror = false;
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shtuka_speredi.render(f5);
    Shtuka_szadi.render(f5);
    Shtuka_sverhu1.render(f5);
    Shtuka_svehu2.render(f5);
    Brov-R.render(f5);
    Brov-L.render(f5);
    Rpg-R0.render(f5);
    Rog-R1.render(f5);
    Rog-R1-2.render(f5);
    Rog-R2.render(f5);
    Rog-R2-3.render(f5);
    Rog-R3.render(f5);
    Rog-R4.render(f5);
    Rog-R5.render(f5);
    Rog-L0.render(f5);
    Rog-L1.render(f5);
    Rog-L1-2.render(f5);
    Rog-L2.render(f5);
    Rog-L2-3.render(f5);
    Rog-L3.render(f5);
    Rog-L4.render(f5);
    Rog-L5.render(f5);
    head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
