// Date: 01.07.2018 0:20:58
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelImperialKnightsArmor_Chestplate extends ModelBase
{
  //fields
    ModelRenderer 1-1;
    ModelRenderer 1-2;
    ModelRenderer 2-1;
    ModelRenderer 2-2;
    ModelRenderer 3-1;
    ModelRenderer 3-2;
    ModelRenderer 4-1;
    ModelRenderer 4-2;
    ModelRenderer 5-1;
    ModelRenderer 5-2;
    ModelRenderer 6-1;
    ModelRenderer 6-2;
    ModelRenderer 6-3;
    ModelRenderer Venok-F;
    ModelRenderer Venok-B;
    ModelRenderer Venok-R;
    ModelRenderer Venok-L;
    ModelRenderer head;
  
  public ModelImperialKnightsArmor_Chestplate()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      1-1 = new ModelRenderer(this, 0, 30);
      1-1.addBox(0F, 0F, 0F, 1, 1, 1);
      1-1.setRotationPoint(-0.5F, -9F, -3F);
      1-1.setTextureSize(64, 32);
      1-1.mirror = true;
      setRotation(1-1, 0F, 0F, 0F);
      1-2 = new ModelRenderer(this, 0, 25);
      1-2.addBox(0F, 0F, 0F, 2, 4, 1);
      1-2.setRotationPoint(-1F, -13F, -3F);
      1-2.setTextureSize(64, 32);
      1-2.mirror = true;
      setRotation(1-2, 0F, 0F, 0F);
      2-1 = new ModelRenderer(this, 0, 23);
      2-1.addBox(0F, 0F, 0F, 2, 1, 1);
      2-1.setRotationPoint(-1F, -9F, -2F);
      2-1.setTextureSize(64, 32);
      2-1.mirror = true;
      setRotation(2-1, 0F, 0F, 0F);
      2-2 = new ModelRenderer(this, 0, 17);
      2-2.addBox(0F, 0F, 0F, 3, 5, 1);
      2-2.setRotationPoint(-1.5F, -14F, -2F);
      2-2.setTextureSize(64, 32);
      2-2.mirror = true;
      setRotation(2-2, 0F, 0F, 0F);
      3-1 = new ModelRenderer(this, 6, 30);
      3-1.addBox(0F, 0F, 0F, 2, 1, 1);
      3-1.setRotationPoint(-1F, -9F, -1F);
      3-1.setTextureSize(64, 32);
      3-1.mirror = true;
      setRotation(3-1, 0F, 0F, 0F);
      3-2 = new ModelRenderer(this, 6, 24);
      3-2.addBox(0F, 0F, 0F, 3, 5, 1);
      3-2.setRotationPoint(-1.5F, -14F, -1F);
      3-2.setTextureSize(64, 32);
      3-2.mirror = true;
      setRotation(3-2, 0F, 0F, 0F);
      4-1 = new ModelRenderer(this, 14, 30);
      4-1.addBox(0F, 0F, 0F, 3, 1, 1);
      4-1.setRotationPoint(-1.5F, -9F, 0F);
      4-1.setTextureSize(64, 32);
      4-1.mirror = true;
      setRotation(4-1, 0F, 0F, 0F);
      4-2 = new ModelRenderer(this, 14, 23);
      4-2.addBox(0F, 0F, 0F, 4, 6, 1);
      4-2.setRotationPoint(-2F, -15F, 0F);
      4-2.setTextureSize(64, 32);
      4-2.mirror = true;
      setRotation(4-2, 0F, 0F, 0F);
      5-1 = new ModelRenderer(this, 24, 30);
      5-1.addBox(0F, 0F, 0F, 3, 1, 1);
      5-1.setRotationPoint(-1.5F, -9F, 1F);
      5-1.setTextureSize(64, 32);
      5-1.mirror = true;
      setRotation(5-1, 0F, 0F, 0F);
      5-2 = new ModelRenderer(this, 24, 23);
      5-2.addBox(0F, 0F, 0F, 4, 6, 1);
      5-2.setRotationPoint(-2F, -15F, 1F);
      5-2.setTextureSize(64, 32);
      5-2.mirror = true;
      setRotation(5-2, 0F, 0F, 0F);
      6-1 = new ModelRenderer(this, 34, 30);
      6-1.addBox(0F, 0F, 0F, 4, 1, 1);
      6-1.setRotationPoint(-2F, -9F, 2F);
      6-1.setTextureSize(64, 32);
      6-1.mirror = true;
      setRotation(6-1, 0F, 0F, 0F);
      6-2 = new ModelRenderer(this, 34, 23);
      6-2.addBox(0F, 0F, 0F, 5, 6, 1);
      6-2.setRotationPoint(-2.5F, -15F, 2F);
      6-2.setTextureSize(64, 32);
      6-2.mirror = true;
      setRotation(6-2, 0F, 0F, 0F);
      6-3 = new ModelRenderer(this, 34, 20);
      6-3.addBox(0F, 0F, 0F, 4, 2, 1);
      6-3.setRotationPoint(-2F, -16.3F, 3.6F);
      6-3.setTextureSize(64, 32);
      6-3.mirror = true;
      setRotation(6-3, -0.8726646F, 0F, 0F);
      Venok-F = new ModelRenderer(this, 32, 0);
      Venok-F.addBox(0F, 0F, 0F, 10, 3, 1);
      Venok-F.setRotationPoint(-5F, -9F, -5F);
      Venok-F.setTextureSize(64, 32);
      Venok-F.mirror = true;
      setRotation(Venok-F, 0F, 0F, 0F);
      Venok-B = new ModelRenderer(this, 32, 4);
      Venok-B.addBox(0F, 0F, 0F, 10, 3, 1);
      Venok-B.setRotationPoint(-5F, -9F, 4F);
      Venok-B.setTextureSize(64, 32);
      Venok-B.mirror = true;
      setRotation(Venok-B, 0F, 0F, 0F);
      Venok-R = new ModelRenderer(this, 24, 8);
      Venok-R.addBox(0F, 0F, 0F, 1, 3, 8);
      Venok-R.setRotationPoint(-5F, -9F, -4F);
      Venok-R.setTextureSize(64, 32);
      Venok-R.mirror = true;
      setRotation(Venok-R, 0F, 0F, 0F);
      Venok-L = new ModelRenderer(this, 42, 8);
      Venok-L.addBox(0F, 0F, 0F, 1, 3, 8);
      Venok-L.setRotationPoint(4F, -9F, -4F);
      Venok-L.setTextureSize(64, 32);
      Venok-L.mirror = true;
      setRotation(Venok-L, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    1-1.render(f5);
    1-2.render(f5);
    2-1.render(f5);
    2-2.render(f5);
    3-1.render(f5);
    3-2.render(f5);
    4-1.render(f5);
    4-2.render(f5);
    5-1.render(f5);
    5-2.render(f5);
    6-1.render(f5);
    6-2.render(f5);
    6-3.render(f5);
    Venok-F.render(f5);
    Venok-B.render(f5);
    Venok-R.render(f5);
    Venok-L.render(f5);
    head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
