// Date: 30.04.2018 7:55:44
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelBretonniaHelmet extends ModelBase
{
  //fields
    ModelRenderer F1;
    ModelRenderer F2;
    ModelRenderer R1;
    ModelRenderer R2;
    ModelRenderer L1;
    ModelRenderer L2;
    ModelRenderer B1;
    ModelRenderer B2;
    ModelRenderer RF2;
    ModelRenderer LF2;
    ModelRenderer LB2;
    ModelRenderer BR2;
    ModelRenderer RF1;
    ModelRenderer FL1;
    ModelRenderer LB1;
    ModelRenderer BR1;
    ModelRenderer U1;
    ModelRenderer U2;
  
  public ModelBretonniaHelmet()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      F1 = new ModelRenderer(this, 42, 9);
      F1.addBox(0F, 0F, 0F, 8, 1, 3);
      F1.setRotationPoint(-4F, -7F, -7F);
      F1.setTextureSize(64, 32);
      F1.mirror = true;
      setRotation(F1, 0F, 0F, 0F);
      F2 = new ModelRenderer(this, 32, 14);
      F2.addBox(0F, 0F, 0F, 8, 1, 1);
      F2.setRotationPoint(-4F, -8F, -5F);
      F2.setTextureSize(64, 32);
      F2.mirror = true;
      setRotation(F2, 0F, 0F, 0F);
      R1 = new ModelRenderer(this, 42, 0);
      R1.addBox(0F, 0F, 0F, 3, 1, 8);
      R1.setRotationPoint(-7F, -7F, -4F);
      R1.setTextureSize(64, 32);
      R1.mirror = true;
      setRotation(R1, 0F, 0F, 0F);
      R2 = new ModelRenderer(this, 32, 5);
      R2.addBox(0F, 0F, 0F, 1, 1, 8);
      R2.setRotationPoint(-5F, -8F, -4F);
      R2.setTextureSize(64, 32);
      R2.mirror = true;
      setRotation(R2, 0F, 0F, 0F);
      L1.mirror = true;
      L1 = new ModelRenderer(this, 42, 0);
      L1.addBox(0F, 0F, 0F, 3, 1, 8);
      L1.setRotationPoint(4F, -7F, -4F);
      L1.setTextureSize(64, 32);
      L1.mirror = true;
      setRotation(L1, 0F, 0F, 0F);
      L1.mirror = false;
      L2.mirror = true;
      L2 = new ModelRenderer(this, 32, 5);
      L2.addBox(0F, 0F, 0F, 1, 1, 8);
      L2.setRotationPoint(4F, -8F, -4F);
      L2.setTextureSize(64, 32);
      L2.mirror = true;
      setRotation(L2, 0F, 0F, 0F);
      L2.mirror = false;
      B1 = new ModelRenderer(this, 42, 9);
      B1.addBox(0F, 0F, 0F, 8, 1, 3);
      B1.setRotationPoint(4F, -7F, 7F);
      B1.setTextureSize(64, 32);
      B1.mirror = true;
      setRotation(B1, 0F, 3.141593F, 0F);
      B2 = new ModelRenderer(this, 32, 14);
      B2.addBox(0F, 0F, 0F, 8, 1, 1);
      B2.setRotationPoint(4F, -8F, 5F);
      B2.setTextureSize(64, 32);
      B2.mirror = true;
      setRotation(B2, 0F, 3.14741F, 0F);
      RF2 = new ModelRenderer(this, 36, 0);
      RF2.addBox(0F, 0F, 0F, 2, 1, 1);
      RF2.setRotationPoint(-6F, -7F, -5F);
      RF2.setTextureSize(64, 32);
      RF2.mirror = true;
      setRotation(RF2, 0F, 0F, 0F);
      LF2.mirror = true;
      LF2 = new ModelRenderer(this, 36, 0);
      LF2.addBox(0F, 0F, 0F, 2, 1, 1);
      LF2.setRotationPoint(4F, -7F, -5F);
      LF2.setTextureSize(64, 32);
      LF2.mirror = true;
      setRotation(LF2, 0F, 0F, 0F);
      LF2.mirror = false;
      LB2.mirror = true;
      LB2 = new ModelRenderer(this, 36, 0);
      LB2.addBox(0F, 0F, 0F, 2, 1, 1);
      LB2.setRotationPoint(4F, -7F, 4F);
      LB2.setTextureSize(64, 32);
      LB2.mirror = true;
      setRotation(LB2, 0F, 0F, 0F);
      LB2.mirror = false;
      BR2 = new ModelRenderer(this, 36, 0);
      BR2.addBox(0F, 0F, 0F, 2, 1, 1);
      BR2.setRotationPoint(-6F, -7F, 4F);
      BR2.setTextureSize(64, 32);
      BR2.mirror = true;
      setRotation(BR2, 0F, 0F, 0F);
      RF1 = new ModelRenderer(this, 32, 0);
      RF1.addBox(0F, 0F, 0F, 1, 1, 1);
      RF1.setRotationPoint(-5F, -7F, -6F);
      RF1.setTextureSize(64, 32);
      RF1.mirror = true;
      setRotation(RF1, 0F, 0F, 0F);
      FL1 = new ModelRenderer(this, 32, 0);
      FL1.addBox(0F, 0F, 0F, 1, 1, 1);
      FL1.setRotationPoint(4F, -7F, -6F);
      FL1.setTextureSize(64, 32);
      FL1.mirror = true;
      setRotation(FL1, 0F, 0F, 0F);
      LB1.mirror = true;
      LB1 = new ModelRenderer(this, 32, 0);
      LB1.addBox(0F, 0F, 0F, 1, 1, 1);
      LB1.setRotationPoint(4F, -7F, 5F);
      LB1.setTextureSize(64, 32);
      LB1.mirror = true;
      setRotation(LB1, 0F, 0F, 0F);
      LB1.mirror = false;
      BR1 = new ModelRenderer(this, 32, 0);
      BR1.addBox(0F, 0F, 0F, 1, 1, 1);
      BR1.setRotationPoint(-5F, -7F, 5F);
      BR1.setTextureSize(64, 32);
      BR1.mirror = true;
      setRotation(BR1, 0F, 0F, 0F);
      U1 = new ModelRenderer(this, 0, 0);
      U1.addBox(0F, 0F, 0F, 8, 1, 8);
      U1.setRotationPoint(-4F, -9F, -4F);
      U1.setTextureSize(64, 32);
      U1.mirror = true;
      setRotation(U1, 0F, 0F, 0F);
      U2 = new ModelRenderer(this, 0, 9);
      U2.addBox(0F, 0F, 0F, 6, 1, 6);
      U2.setRotationPoint(-3F, -10F, -3F);
      U2.setTextureSize(64, 32);
      U2.mirror = true;
      setRotation(U2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    F1.render(f5);
    F2.render(f5);
    R1.render(f5);
    R2.render(f5);
    L1.render(f5);
    L2.render(f5);
    B1.render(f5);
    B2.render(f5);
    RF2.render(f5);
    LF2.render(f5);
    LB2.render(f5);
    BR2.render(f5);
    RF1.render(f5);
    FL1.render(f5);
    LB1.render(f5);
    BR1.render(f5);
    U1.render(f5);
    U2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
