// Date: 08.06.2018 23:17:41
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelPistolet gnomii extends ModelBase
{
  //fields
    ModelRenderer Stvol;
    ModelRenderer Konec_stvola;
    ModelRenderer Kub_poseredine;
    ModelRenderer Rukoyatka1;
    ModelRenderer Rukoyatka2;
    ModelRenderer Mejdu_rukoyatkoi_i_stvolom;
    ModelRenderer Kurok1;
    ModelRenderer Kurok2;
  
  public ModelPistolet gnomii()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Stvol = new ModelRenderer(this, 0, 0);
      Stvol.addBox(0F, 0F, 0F, 2, 2, 9);
      Stvol.setRotationPoint(-1F, 16F, -6F);
      Stvol.setTextureSize(64, 32);
      Stvol.mirror = true;
      setRotation(Stvol, 0F, 0F, 0F);
      Konec_stvola = new ModelRenderer(this, 0, 17);
      Konec_stvola.addBox(0F, 0F, 0F, 3, 3, 1);
      Konec_stvola.setRotationPoint(-1.5F, 15.5F, -7F);
      Konec_stvola.setTextureSize(64, 32);
      Konec_stvola.mirror = true;
      setRotation(Konec_stvola, 0F, -0.0174533F, 0F);
      Kub_poseredine = new ModelRenderer(this, 0, 11);
      Kub_poseredine.addBox(0F, 0F, 0F, 3, 3, 3);
      Kub_poseredine.setRotationPoint(-1.5F, 15.5F, -1F);
      Kub_poseredine.setTextureSize(64, 32);
      Kub_poseredine.mirror = true;
      setRotation(Kub_poseredine, 0F, -0.0174533F, 0F);
      Rukoyatka1 = new ModelRenderer(this, 13, 0);
      Rukoyatka1.addBox(0F, 0F, 0F, 2, 5, 1);
      Rukoyatka1.setRotationPoint(-1F, 16F, 3F);
      Rukoyatka1.setTextureSize(64, 32);
      Rukoyatka1.mirror = true;
      setRotation(Rukoyatka1, 0F, 0F, 0F);
      Rukoyatka2 = new ModelRenderer(this, 19, 0);
      Rukoyatka2.addBox(0F, 0F, 0F, 2, 3, 1);
      Rukoyatka2.setRotationPoint(-1F, 17F, 4F);
      Rukoyatka2.setTextureSize(64, 32);
      Rukoyatka2.mirror = true;
      setRotation(Rukoyatka2, 0F, 0F, 0F);
      Mejdu_rukoyatkoi_i_stvolom = new ModelRenderer(this, 25, 0);
      Mejdu_rukoyatkoi_i_stvolom.addBox(0F, 0F, 0F, 2, 1, 1);
      Mejdu_rukoyatkoi_i_stvolom.setRotationPoint(-1F, 18F, 2F);
      Mejdu_rukoyatkoi_i_stvolom.setTextureSize(64, 32);
      Mejdu_rukoyatkoi_i_stvolom.mirror = true;
      setRotation(Mejdu_rukoyatkoi_i_stvolom, 0F, 0F, 0F);
      Kurok1 = new ModelRenderer(this, 0, 4);
      Kurok1.addBox(0F, 0F, 0F, 1, 2, 1);
      Kurok1.setRotationPoint(-0.5F, 18F, -0.5F);
      Kurok1.setTextureSize(64, 32);
      Kurok1.mirror = true;
      setRotation(Kurok1, 0F, 0F, 0F);
      Kurok2 = new ModelRenderer(this, 0, 0);
      Kurok2.addBox(0F, 0F, 0F, 1, 1, 3);
      Kurok2.setRotationPoint(-0.5F, 19F, 0.5F);
      Kurok2.setTextureSize(64, 32);
      Kurok2.mirror = true;
      setRotation(Kurok2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Stvol.render(f5);
    Konec_stvola.render(f5);
    Kub_poseredine.render(f5);
    Rukoyatka1.render(f5);
    Rukoyatka2.render(f5);
    Mejdu_rukoyatkoi_i_stvolom.render(f5);
    Kurok1.render(f5);
    Kurok2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
